### ISSUE TITLE
a minor bug with check OS version stuffs

### ISSUE THREAD

**Issue by 739480474** [DarthTon/Xenos#1]
a BSOD BUG in driver:
#if defined(_WIN7_)
if (ver_short != WINVER_7 && ver_short != WINVER_7_SP1)
{
        if(ver_short == WINVER_7_SP1 && buildNo != 18700)
        pData->correctBuild = FALSE;
        return STATUS_NOT_SUPPORTED;
}
#elif defined(_WIN8_)

the 'buildNo' will never be check, so BSOD in my win7 x64 OS.

FIX:
#if defined(_WIN7_)
if (ver_short != WINVER_7 && ver_short != WINVER_7_SP1)
        return STATUS_NOT_SUPPORTED;
if (ver_short == WINVER_7_SP1 && buildNo != 18700)
        pData->correctBuild = FALSE;
#elif defined(_WIN8_)

BTW, I think if you update a new OFFSET for unsupported OS is more better for this 'FIX'....

**Comment by DarthTon** [comment]
Fixed in 7f3a4202f57220225ba72d3e665af144f9b8635d. This 'fix' is designed to prevent BSODs when new build comes out and offsets aren't updated yet. Also only last build version is supported for each major OS because I don't want to track and test dozens of builds.

**Comment by 739480474** [comment]
thanks!!
