### ISSUE TITLE
Failed to load driver w10

### ISSUE THREAD

**Issue by R00T88** [DarthTon/Xenos#11]
Hello man,
when i try to select Kernel mode injection i got always this errore in log file

2016-01-10 22:55:51 *NORMAL*     Started on Windows 10.0.0.10586 x64. Driver status: 0xC000012F
2016-01-10 22:55:58 *ERROR*      Failed to load BlackBone driver:

The image file was not specified in the correct format, it did not have an initial MZ.

i run the injector with administrative priviledge.
Another thing is "protect self" under tools menu is always disable

Regards

**Comment by R00T88** [comment]
These happend because BlackBoneDrv project is not included either in BlackBone/Xenos project and it not rebuild it

**Comment by DarthTon** [comment]
I don't want to include driver project into blackbone/xenos solutions because it has completely different solution build configurations (i.e. build configs for different OS). So it must be built manually before xenos can embed it into resources.
On the other hand I can disable driver overwriting if there is driver file already present on disk.

**Comment by R00T88** [comment]
Ok thank you for your time and fixes!

**Comment by Reckt25** [comment]
Hi i get allways a BlueScreen when i try to inject via the Driver

 page_fault_in_nonpaged_area

Win 10 64bit Build 10586

**Comment by R00T88** [comment]
into function DlgSettings::OnInit i add this check to prevent using driver injection method if you don't have a valid driver

if(NT_SUCCESS(blackbone::Driver().status()))
	{
		_injectionType.Add(L"Kernel (CreateThread)", Kernel_Thread);
		_injectionType.Add(L"Kernel (APC)", Kernel_APC);
		_injectionType.Add(L"Kernel (Manual map)", Kernel_MMap);
		//_injectionType.Add( L"Kernel driver manual map", Kernel_DriverMap );
	}

Regards

**Comment by Reckt25** [comment]
Nice Thx

**Comment by DarthTon** [comment]
BSOD fixed in 1790ddcdc41a1ff2630b9917039bd28aca668177
