### ISSUE TITLE
Bugfixes

### ISSUE THREAD

**Issue by R00T88** [DarthTon/Xenos#12]
Hello man,
Ii found some bug that could be addressed like this:

1. function MainDlg::Inject() at top of it i add:

if (_procList.selection() == -1)
	{
		Message::ShowError(_hwnd, L"Select process first!");
		return;
	}

SaveConfig();

so it check if process is selected and the save config to be sure runtime changes on process selection and image selection are reflected

2. function InjectionCore::GetTargetProcess calling CreateProcessW() on error copy this:

status = LastNtStatus();
Message::ShowError( _hMainDlg, L"Failed to create new process.\n" + blackbone::Utils::GetErrorDescription(status) );
return status;

otherwise it return 0 instead error

3. function MainDlg::OnSelectExecutable change if with this:

if (SelectExecutable( path ))
        SetActiveProcess( 0, path );
else
	_procList.reset();

Hope this could help

Regards

**Comment by R00T88** [comment]
4. function MainDlg::OnClose save only if data are correct

	if(_procList.selection() != -1 && _modules.selection() != -1)
		SaveConfig();

**Comment by DarthTon** [comment]
Fixed in 1790ddcdc41a1ff2630b9917039bd28aca668177
