### ISSUE TITLE
Bugfixes v2.2.1

### ISSUE THREAD

**Issue by R00T88** [DarthTon/Xenos#13]
Hello man,
thx for take into consideration my fixes.
i found 3 another bugs

1. function MainDlg::LoadImageFile check if process is selected before enable inject button

	if (_procList.selection() != -1)
		_inject.enable();

2. function InjectionCore::GetTargetProcess if you get error calling CreateProcessW() it return 0 and not errorcode so i fix it like this

status = LastNtStatus();
Message::ShowError( _hMainDlg, L"Failed to create new process.\n" + blackbone::Utils::GetErrorDescription(status) );
return status;

3. function DlgSettings::OnInit i add this check to prevent using driver injection method if you don't have a valid driver

if(NT_SUCCESS(blackbone::Driver().status()))
{
_injectionType.Add(L"Kernel (CreateThread)", Kernel_Thread);
_injectionType.Add(L"Kernel (APC)", Kernel_APC);
_injectionType.Add(L"Kernel (Manual map)", Kernel_MMap);
//_injectionType.Add( L"Kernel driver manual map", Kernel_DriverMap );
}

Hope this improve your amazing work

Regards

**Comment by DarthTon** [comment]
Fixed in f40e57c0b5f2ed920f72ee73b1635534bce59d3b. Injector  checks for loaded driver every time you select any of the driver injection methods. And if driver isn't loaded, selection is reverted to non-driver one.
