### ISSUE TITLE
Process Watcher and Auto Injection?

### ISSUE THREAD

**Issue by mirh** [DarthTon/Xenos#15]
I casually stumbled over an older version of this fantastic tool (1.0.1.4 iirc) and I remember there was this option to automatically inject dlls as soon as the selected exe started. 

Would it be possible to add this again? Perhaps I dunno, a simple checkbox next to *Manual launch*?
In particular it would be very useful in The Division, since shortly after launch the executable is killed and started again by uplay client, and this fools basically every automatic inject-once-and-forgot tool. 

Thank you.

**Comment by DarthTon** [comment]
But it is still available in main dialog window.

**Comment by mirh** [comment]
Mhh perhaps I didn't explain well enough. 
I see Manual Launch is indeed doing that. But the "problem" is that once it injects once, it *disarm* itself. 
And you have to press it two times to have the thing working in my case (or just one I mean, provided you have sense of timing).

**Comment by DarthTon** [comment]
Added process skipping to config in 4b1f24c29254a9df249b2f9e382f140f36e004e2.

**Comment by mirh** [comment]
Cool. But.. I had something even simpler and straightforward in my mind to be honest :s
Wouldn't it just be easier if the program *automatically* continued to inject the dlls everytime it found a new process of the selected executable?

**Comment by DarthTon** [comment]
Yeah, I'll add a continuous injection option alongside.

**Comment by luastoned** [comment]
Once a process closes and you hit inject (with the old PID) Xenos sorta gets stuck and crashes down the road.

No idea if there is a check if the process still exists, but you know the executable's path so check for new processes of that? Pretty much the Process Watcher @mirh suggested.

**Comment by DarthTon** [comment]
Added continuous injection option and fixed some bugs in 55756c10d4aa270e71e5ccf4c4e3f90519a6db3a.

**Comment by mirh** [comment]
Cool! It's really noob-proof now. 
May I suggest to gray out *skip count* when *Inject indefinitely* is selected?

**Comment by DarthTon** [comment]
It can work simultaneously. Like skip first process and the inject into each subsequent.

**Comment by mirh** [comment]
Oh.. You are right. 
Thanks!
