### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Wbdn** [DarthTon/Xenos#19]
from log
Failed to inject image using manual map, status: 0xC0000225
is this my problem?

**Comment by R00T88** [comment]
i have same errorcode with manualmap on windows 10.

**Comment by DarthTon** [comment]
Any manual map tracing info available?

**Comment by R00T88** [comment]
from log i have this: 2016-03-02 00:18:37 *ERROR*      Failed to inject image using default injection, status: 0xC0000135

**Comment by R00T88** [comment]
it was a dll related problem with a dynamic lib included into project.
I remove .lib and re-compile, work now.
Blackbone check for depency missing or invalid?

**Comment by DarthTon** [comment]
No, blackbone doesn't check for missing imports, but it returns eeror code if import is missing during injection.
