### ISSUE TITLE
WIN7 x64 Kernel(APC) injection type issues

### ISSUE THREAD

**Issue by 739480474** [DarthTon/Xenos#2]
WIN7 x64 Kernel(APC) inject to notepad.exe(x64), notepad crash.

WIN7 x64 Kernel(APC) inject to cmd.exe failed(not crash)
but with very strange behavier:
It print a "More ? " string after by each inject operatiion in the cmd window!!!

I checked any system or user level hook with a adv tools, and I shutdown any secure softwares.

**Comment by DarthTon** [comment]
APC is somewhat unreliable. Have you tried other injection methods?

**Comment by DarthTon** [comment]
Outdated
