### ISSUE TITLE
Windows7 x64 Manual Mapping Thread Dead Bug

### ISSUE THREAD

**Issue by kainpark7894** [DarthTon/Xenos#22]
User Manual Mapping & Kernel Manual Mapping

Test OS:windows 7 x64 ultimate

32bit & 64bit dll File Manual Mapping No option Injection

But 10~20 Time -> ManualMapping dll Thread Dead 

Extreme Injector ManualMapping dll Thread no dead

test.dll file cmd.exe <-- manual mapping injection!

Thank you test.zip file upload 

[test.zip](https://github.com/DarthTon/Xenos/files/216440/test.zip)

**Comment by DarthTon** [comment]
Duplicates https://github.com/DarthTon/Blackbone/issues/79
