### ISSUE TITLE
Error Loading BlackBone after Windows 10 Anniversary Update

### ISSUE THREAD

**Issue by SippieCup** [DarthTon/Xenos#23]
After installing the W10 AU whenever I try to use kernel injection methods the blackbone driver fails.

Error message:

```
Failed to load BlackBone driver:

The request is not supported.
```

Any Idea what could be happening? it seems like a local issue.

**Comment by DarthTon** [comment]
Probably offsets are off. I'll fix when get AU myself.

**Comment by DarthTon** [comment]
Should load after 1b7931a63d76b088a8b695177be831dfd8cc366c

**Comment by SippieCup** [comment]
I'll try it out now.

**Comment by SippieCup** [comment]
Bluescreen - Pagefault.

http://i.imgur.com/ocDtIhu.jpg?1

**Comment by DarthTon** [comment]
Did you recompile the driver?

**Comment by SippieCup** [comment]
Yes, that was with the new recompiled driver.

Could it be an issue with what was injected? I'll try the test app.

**Comment by SippieCup** [comment]
Hum. I think i actually just used the .sys that was generated by your build.

I recompiled Xenos64 and blackbone with the latest commits and now I am getting a different error.

I did change the target platform version to the updated version, 10.0.14393.0 - bu other than that everything is as is. Compiling blackbone to a .lib & the xenos exe.

![xenos error](https://cloud.githubusercontent.com/assets/679311/17459453/cb5ef518-5c06-11e6-924a-4b1b2ca210e8.PNG)

This is the error I now get when trying to load the Driver. Using the precompiled .sys I can get past this, but it causes a page fault.

**Comment by SippieCup** [comment]
Alright,

Realized the issue with that previous error was my release configuration for the driver being wrong.

Fixed that, loads driver again, still BSOD on use.

**Comment by DarthTon** [comment]
Can you give me you test dll?

**Comment by SippieCup** [comment]
I found the issue. I use license protection via VMProtect 3.0, if I apply the protection it will page fault, without it works fine.

Using the test app, if you recompile to MMap the linked calc.exe you can reproduce the pagefault.
https://1drv.ms/u/s!AsgDc2tEZfzMqnqdSlewXVgMotGB

**Comment by DarthTon** [comment]
Doesn't BSOD on my test system. But executable doesn't launch normally either. Maybe you can pack something more simple?

**Comment by Famous02** [comment]
Hmmm DarthTon Do U Have A Tutorial FOr How To Compile ??

**Comment by mirh** [comment]
Install Visual Studio 2015 (or even 2013 iirc)
Download Xenos sources
Download [Blackbone](https://github.com/DarthTon/Blackbone) sources. 
Put both folders in the same directory and remove "-master" suffix from their names. 

Open Xenos.sln
Compile
Profit

Binaries of latest version are already [here](http://community.pcgamingwiki.com/files/file/654-octa-core-faker-singledualtri-core-fix/) anyway.

**Comment by Finleyyy** [comment]
Errors if I try to compile the sources
