### ISSUE TITLE
Xenos as a standalone lib

### ISSUE THREAD

**Issue by Think7** [DarthTon/Xenos#24]
Hello,

Can Xenos be used as a standalone library? For example if i wanted to write my own application and have Xenos only handle the DLL injection process.

After compilation a .LIB file is created in the directory but im not sure which headers are needed / if there is a single simple include.

Thanks for your time and creating this library!

**Comment by DarthTon** [comment]
Xenos is mostly a GUI. Blackbone does all the injection work. And it is a standalone library.
