### ISSUE TITLE
Add Blackbone repo as submodule

### ISSUE THREAD

**Issue by mirh** [DarthTon/Xenos#25]
It's a required dependency, it might as well be included. 
https://github.com/blog/2104-working-with-submodules

EDIT: it [should](https://git-scm.com/docs/git-submodule#git-submodule--b) be possible to have it pointing to latest master branch too, instead of only a prefixed commit

**Comment by DarthTon** [comment]
I'm still not sure that'll be a good idea. Blacbone lib is updated more often that xenos and -b' flag only allows to a specify different branch than master but commit is still fixed.

**Comment by mirh** [comment]
According to [this](http://stackoverflow.com/questions/9189575/git-submodule-tracking-latest), there's really nothing special with master branch. 

Then, tbh, I never really understood the point in subtrees. Why even keep the repos separated if you have to copy (and include) whole history of B?
