### ISSUE TITLE
Failed to Load BlackBone Driver

### ISSUE THREAD

**Issue by complexitydev** [DarthTon/Xenos#26]
Failed to Load BlackBone Driver:

The specified image file did not have the correct format, it did not have an initial MZ. 

Not sure what I'm doing from. Using dsefix to disable signing, tried it in test mode also. I compiled both blackdone and Xenos as source with no errors.

**Comment by ahmetabdi** [comment]
Same here, strangely the file 'BlackBoneDrv10.sys' file in the folder get's deleted after the message any ideas @DarthTon

**Comment by DarthTon** [comment]
So the driver file is still present when messagebox gets shown? Can you post that file somewhere?

**Comment by ahmetabdi** [comment]
@DarthTon Yes the driver file stays till you hit 'OK' on the message box.

I'm using the driver file from here https://github.com/DarthTon/Blackbone/tree/master/src/BlackBoneDrv/bin/x64/Win10Release

Currently running `Microsoft Windows [Version 10.0.14393]`

Uploaded the version in the folder if it makes a difference: http://www113.zippyshare.com/v/DM6g5moP/file.html

**Comment by DarthTon** [comment]
The thing is, your uploaded file is just a git LFS link.
```
version https://git-lfs.github.com/spec/v1
oid sha256:ddd5fd10e9f1825bc59d58912c807c3e2cde159d2fe2f85596336bd98d43fa5b
size 62832
```
How did you get that file from repo?

**Comment by ahmetabdi** [comment]
oh never knew that, lemme try clone instead

**Comment by DarthTon** [comment]
I wasn't aware of that too. There was an issue about this even https://github.com/git-lfs/git-lfs/issues/903. They haven't fixed it yet it seems.

**Comment by ahmetabdi** [comment]
All good now thanks 👍

**Comment by Phantoms123** [comment]
can anyone help to install blackbone to work with xenos?
