### ISSUE TITLE
When i select Injection mode to kernel mode, then send me a error msg.

### ISSUE THREAD

**Issue by the7shfun** [DarthTon/Xenos#28]
---------------------------
Error
---------------------------
Failed to load BlackBone driver:

Windows 无法验证此文件的数字签名。某软件或硬件最近有所更改，可能安装了签名错误或损毁的文件，或者安装的文件可能是来路不明的恶意软件。

Google Translate:
(Failed to verify the digital signature of this file. A software or hardware has recently changed, may have installed a signed error or damaged file, or the installation of the file may be unknown malware.)

First time it's show up on my Win10 x64.

And then i switch my system to WIN7 X64 same error pop up.

I dont know what it's , how can i fix it?

**Comment by verysimplenick** [comment]
[How to disable driver verification](https://www.howtogeek.com/167723/how-to-disable-driver-signature-verification-on-64-bit-windows-8.1-so-that-you-can-install-unsigned-drivers/)

**Comment by the7shfun** [comment]
Thank for that.
But still not fix my issue.
Cause i already try on WIN7 x64 and if i send injecter to my freinds , they still need do disable driver verification or not?
