### ISSUE TITLE
Failed to inject image using default injection, status: 0xC0000135

### ISSUE THREAD

**Issue by luastoned** [DarthTon/Xenos#29]
I'm trying to inject a dll without any special config, it's linked with a static lib but nothing out of the ordinary.

    10:21:52 *NORMAL*     Started on Windows 10.0.0.15063 x64. Driver status: 0xC0000225
    10:24:22 *CRITICAL*   Injection initiated. Mode: 0, process type: 0, pid: xxxx, mmap flags: 0x4, erasePE: 0, unlink: 0, thread hijack: 0, init routine: '', init arg: ''
    10:24:22 *CRITICAL*   Injecting image 'C:\Code\DebugProj\Release\DebugProj.dll'
    10:24:22 *ERROR*      Failed to inject image using default injection, status: 0xC0000135
    10:24:22 *ERROR*      Failed to inject image 'C:\Code\DebugProj\Release\DebugProj.dll'.
    Error code 0xC0000135

**Comment by DarthTon** [comment]
It failed to load some dependency dll.

**Comment by luastoned** [comment]
What can I do to solve the issue?

**Comment by DarthTon** [comment]
Make sure dependencies are accessible from target process location.

**Comment by Miiiiike** [comment]
how did I do that

**Comment by Miiiiike** [comment]
i need some help :/

**Comment by TheWebs** [comment]
i ran into this problem as well

**Comment by TheWebs** [comment]
Turned out to be my dll that had the wrong address function
