### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by febitanya** [DarthTon/Xenos#3]
Error	3	error LNK2019: unresolved external symbol "public: static class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __cdecl blackbone::Utils::UTF8ToWstring(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?UTF8ToWstring@Utils@blackbone@@SA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) referenced in function "class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __cdecl acut::ensure_tchar<wchar_t>(char const *)" (??$ensure_tchar@_W@acut@@YA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@PBD@Z)	G:\New Folder\Xenos-master\src\ProfileMgr.obj	Xenos

**Comment by DarthTon** [comment]
Are you sure you have blackbone library included as linker dependency?

**Comment by febitanya** [comment]
i added to solution

**Comment by 04255** [comment]
solve it ? i same wrong
