### ISSUE TITLE
Object Name Not Found

### ISSUE THREAD

**Issue by kediragg** [DarthTon/Xenos#30]
When I select the '' kernel '' option on the injector I get this following error = Falied to load heelix driver. Object Name Not Found

Please Help-me

**Comment by DarthTon** [comment]
There is no suitable driver file in injector folder.

**Comment by kediragg** [comment]
I already gave load in the driver but it seems that xenos is not recognizing it

**Comment by kediragg** [comment]
Before that, xenos had already created "heelix.sys" when I clicked to inject by kernel

**Comment by DarthTon** [comment]
Have you modified all driver names, paths, device names to use heelix?
