### ISSUE TITLE
Injecting from a DLL as byte array

### ISSUE THREAD

**Issue by jl2378** [DarthTon/Xenos#35]
I've been trying to use the overloaded Load() method that takes a pointer to an image. I'm getting the error "failed to inject x86 module into native x64 process", but I made sure that my DLL was indeed an x64 module.

Is this feature properly supported?

**Comment by DarthTon** [comment]
It is. Try to inject it with blackbone directly.

**Comment by jl2378** [comment]
Read the code from blackbone and got it working properly. Thanks.
