### ISSUE TITLE
Trying to compile Xenos and 0xC0000001

### ISSUE THREAD

**Issue by 1234filip** [DarthTon/Xenos#39]
So I resolved all the issues regarding inclusion with xenos(which is pain in the ass btw). And now I get these errors: https://pastebin.com/DZYBP62X . because I don't want to solve them all can somebody give me a compiled binary of the newest xenos? Or maybe DarthTon can you start including binaries in the github or a link to them? I'm doing this solely cause I get this error: Error code 0xC0000001 . And I don't have the fall creators update: 
2017-10-30 18:37:31 *NORMAL*     Started on Windows 10.0.0.15063 x64. Driver status: 0xC0000225
And I tried out the solution that the guy proposed on the issue

**Comment by DarthTon** [comment]
You can download 2.3.1 release from https://drive.google.com/open?id=0B1mtW4_tmJhSbGVGTUVUMG9CRGc
