### ISSUE TITLE
Cannot load driver

### ISSUE THREAD

**Issue by Mykybo** [DarthTon/Xenos#41]
When selecting `Kernel (Manual Map)` or trying to manually inject the driver (sc create & sc start) I get the following error:

```
2017-11-27 22:02:36 *NORMAL*     Started on Windows 10.0.0.16299 x64. Driver status: 0xC0000225
2017-11-27 22:02:41 *ERROR*      Failed to load BlackBone driver:

Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
```

I got the executable from UC & the driver from Blackbone repo.

**Comment by DarthTon** [comment]
Enable test mode

**Comment by Mykybo** [comment]
well, if this is usable only with test mode, then it is kinda useless :b

**Comment by DarthTon** [comment]
Sign it yourself and use without test mode.
