### ISSUE TITLE
Help 0xC0000135

### ISSUE THREAD

**Issue by Stage4000** [DarthTon/Xenos#62]
Failed to inject image '{path to dll}'. Error code 0xC0000315  

Anyone know what causes this and how I can fix it? I already have every vcredist imaginable.

Windows 10-1809 x64 Injecting Osiris into CS:GO

**Comment by brokeDude2901** [comment]
probably some wrong address function

**Comment by mmiraly** [comment]
I also need help, same issue while trying to inject Osiris

Error code 0xC0000135

**Comment by mmiraly** [comment]
@Stage4000 I found a fix that works for me, Just go to advanced and set the mod to manual map

![image](https://user-images.githubusercontent.com/23267980/92811410-6c875180-f38c-11ea-9941-afd3825d75ca.png)

**Comment by Marcos666** [comment]
I'm trying to inject Spankerfield, onto Battlefield 4.. any solution? If i put Manual Map. the game just crashes. :(

**Comment by Stage4000** [comment]
Did you really need to Necro a 2 year old issue for your unrelated problems?
