### ISSUE TITLE
Failed to inject image - Error code 0xC00000EF

### ISSUE THREAD

**Issue by ExodusTime** [DarthTon/Xenos#70]
been trying to use BlackBone like crazy without luck, getting failed to load blackbone and also something about not being supported (tried Test Mode aswell)

Native Inject or Manual Map wont work either, i just cant get past "Error code 0xC00000EF" every time i try to inject

**Comment by Clownsw** [comment]
我觉得你可以看一下相关代码，我记得代码内含有代码标注
