### ISSUE TITLE
So many errors while compiling

### ISSUE THREAD

**Issue by icemotione** [DarthTon/Xenos#79]
![serror](https://user-images.githubusercontent.com/69984658/107721401-1d649480-6d0f-11eb-925d-17a1fa303f25.png)

It used to work fine, I did a factory reset on my PC and reinstalled VS2019 with the correct workloads & latest windows sdk, why does it output so many errors? Tried googling but can't find a fix.

**Comment by icemotione** [comment]
![23](https://user-images.githubusercontent.com/69984658/107729260-ef894b00-6d22-11eb-8f7e-94adf3f1c2f9.png)
23 Errors left, after #include iterator
How do I fix this?

**Comment by Eddcapone** [comment]
@icemotione Did you fixed it?
