### ISSUE TITLE
GetModuleFileNameA Error with Manual Map

### ISSUE THREAD

**Issue by ConnectDevelopers** [DarthTon/Xenos#8]
void Log::Init(HMODULE hModule)
{
	memset(g_logFile, 0, sizeof(g_logFile));

	if (GetModuleFileNameA(hModule, g_logFile, MAX_PATH) != 0)
	{
		size_t slash = -1;

		for (size_t i = 0; i < strlen(g_logFile); i++)
		{
			if (g_logFile[i] == '/' || g_logFile[i] == '\\')
			{
				slash = i;
			}
		}

		if (slash != -1)
		{
			g_logFile[slash + 1] = '\0';
			strcpy_s(g_debugLogFile, g_logFile);
			strcat_s(g_debugLogFile, "debug.log");
			strcat_s(g_logFile, "hook.log");
		}
		else
		{
			// Shitty manual mapper detected.
			MessageBoxA(nullptr, "Unable to parse target module path", "ERROR", MB_OK);
			ExitProcess(0);
		}
	}
	else
	{
		// Shitty manual mapper detected. | 2much 4 xenos manual map
		MessageBoxA(nullptr, "GetModuleFileNameA failed", "ERROR", MB_OK);
		ExitProcess(0);
	}
}

**Comment by DarthTon** [comment]
'Add loader reference' option will make it compatible.
